In [1]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler, LabelEncoder, OneHotEncoder
import pickle

In [2]:
data=pd.read_csv('Churn_Modelling.csv')
data.head()

,RowNumber,CustomerId,Surname,CreditScore,Geography,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited
0,1,15634602,Hargrave,619,France,Female,42,2,0.00,1,1,1,101348.88,1
1,2,15647311,Hill,608,Spain,Female,41,1,83807.86,1,0,1,112542.58,0
2,3,15619304,Onio,502,France,Female,42,8,159660.80,3,1,0,113931.57,1
3,4,15701354,Boni,699,France,Female,39,1,0.00,2,0,0,93826.63,0
4,5,15737888,Mitchell,850,Spain,Female,43,2,125510.82,1,1,1,79084.10,0

In [3]:
# Preprocess the data
data = data.drop(['RowNumber', 'CustomerId', 'Surname'], axis=1)

In [4]:
# Encode categorical variables
label_encoder_gender = LabelEncoder()
data['Gender'] = label_encoder_gender.fit_transform(data['Gender'])

In [5]:
# One-hot encode 'Geography'
onehot_encoder_geo = OneHotEncoder(handle_unknown='ignore')
geo_encoded = onehot_encoder_geo.fit_transform(data[['Geography']]).toarray()
geo_encoded_df = pd.DataFrame(geo_encoded, columns=onehot_encoder_geo.get_feature_names_out(['Geography']))
geo_encoded_df

      Geography_France  Geography_Germany  Geography_Spain
0                  1.0                0.0              0.0
1                  0.0                0.0              1.0
2                  1.0                0.0              0.0
3                  1.0                0.0              0.0
4                  0.0                0.0              1.0
...                ...                ...              ...
9995               1.0                0.0              0.0
9996               1.0                0.0              0.0
9997               1.0                0.0              0.0
9998               0.0                1.0              0.0
9999               1.0                0.0              0.0

[10000 rows x 3 columns]

In [6]:
# Combine one-hot encoded columns with original data
data = pd.concat([data.drop('Geography', axis=1), geo_encoded_df], axis=1)
data.head()

,CreditScore,Gender,Age,Tenure,Balance,NumOfProducts,HasCrCard,IsActiveMember,EstimatedSalary,Exited,Geography_France,Geography_Germany,Geography_Spain
0,619,0,42,2,0.00,1,1,1,101348.88,1,1.0,0.0,0.0
1,608,0,41,1,83807.86,1,0,1,112542.58,0,0.0,0.0,1.0
2,502,0,42,8,159660.80,3,1,0,113931.57,1,1.0,0.0,0.0
3,699,0,39,1,0.00,2,0,0,93826.63,0,1.0,0.0,0.0
4,850,0,43,2,125510.82,1,1,1,79084.10,0,0.0,0.0,1.0

In [7]:
# Split the data into features and target
X = data.drop('EstimatedSalary', axis=1)
y = data['EstimatedSalary']

In [8]:
## Split the data in training and tetsing sets
X_train,X_test,y_train,y_test=train_test_split(X,y,test_size=0.2,random_state=42)

In [9]:
## Scale these features
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [10]:
# Save the encoders and scaler for later use
with open('label_encoder_gender.pkl', 'wb') as file:
    pickle.dump(label_encoder_gender, file)

with open('onehot_encoder_geo.pkl', 'wb') as file:
    pickle.dump(onehot_encoder_geo, file)

with open('scaler_regression.pkl', 'wb') as file:
    pickle.dump(scaler, file)

## ANN regression problem

In [11]:
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense

2025-06-03 02:55:42.979543: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.

In [12]:
# Build the model
model = Sequential([
    Dense(64, activation='relu', input_shape=(X_train.shape[1],)),
    Dense(32, activation='relu'),
    Dense(1)  # Output layer for regression by default activation function is linear activation 
])

## compile the model
model.compile(optimizer='adam',loss='mean_absolute_error',metrics=['mae'])

model.summary()

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #
=================================================================
 dense (Dense)               (None, 64)                832

 dense_1 (Dense)             (None, 32)                2080

 dense_2 (Dense)             (None, 1)                 33

=================================================================
Total params: 2945 (11.50 KB)
Trainable params: 2945 (11.50 KB)
Non-trainable params: 0 (0.00 Byte)
_________________________________________________________________

In [13]:
from tensorflow.keras.callbacks import EarlyStopping, TensorBoard
import datetime

# Set up TensorBoard
log_dir = "regressionlogs/fit/" + datetime.datetime.now().strftime("%Y%m%d-%H%M%S")
tensorboard_callback = TensorBoard(log_dir=log_dir, histogram_freq=1)

In [14]:
# Set up Early Stopping
early_stopping_callback = EarlyStopping(monitor='val_loss', patience=10, restore_best_weights=True)

In [15]:
# Train the model
history = model.fit(
    X_train, y_train,
    validation_data=(X_test, y_test),
    epochs=100,
    callbacks=[early_stopping_callback, tensorboard_callback]
)

Epoch 1/100
250/250 [==============================] - 1s 3ms/step - loss: 100380.3594 - mae: 100380.3594 - val_loss: 98524.9062 - val_mae: 98524.9062
Epoch 2/100
250/250 [==============================] - 1s 2ms/step - loss: 99654.6641 - mae: 99654.6641 - val_loss: 97043.4141 - val_mae: 97043.4141
Epoch 3/100
250/250 [==============================] - 0s 2ms/step - loss: 97086.6406 - mae: 97086.6406 - val_loss: 93275.9062 - val_mae: 93275.9062
Epoch 4/100
250/250 [==============================] - 0s 2ms/step - loss: 92040.3516 - mae: 92040.3516 - val_loss: 86974.3359 - val_mae: 86974.3359
Epoch 5/100
250/250 [==============================] - 0s 2ms/step - loss: 84623.6250 - mae: 84623.6250 - val_loss: 78845.2812 - val_mae: 78845.2812
Epoch 6/100
250/250 [==============================] - 0s 2ms/step - loss: 75910.7578 - mae: 75910.7578 - val_loss: 70257.8906 - val_mae: 70257.8906
Epoch 7/100
250/250 [==============================] - 0s 2ms/step - loss: 67319.7812 - mae: 67319.7812 - val_loss: 62654.2383 - val_mae: 62654.2383
Epoch 8/100
250/250 [==============================] - 0s 2ms/step - loss: 60253.4336 - mae: 60253.4336 - val_loss: 57035.6875 - val_mae: 57035.6875
Epoch 9/100
250/250 [==============================] - 0s 2ms/step - loss: 55387.3008 - mae: 55387.3008 - val_loss: 53538.0742 - val_mae: 53538.0742
Epoch 10/100
250/250 [==============================] - 0s 2ms/step - loss: 52639.2930 - mae: 52639.2930 - val_loss: 51942.3594 - val_mae: 51942.3594
Epoch 11/100
250/250 [==============================] - 0s 2ms/step - loss: 51348.1914 - mae: 51348.1914 - val_loss: 51317.6719 - val_mae: 51317.6719
Epoch 12/100
250/250 [==============================] - 1s 3ms/step - loss: 50765.3633 - mae: 50765.3633 - val_loss: 51074.6680 - val_mae: 51074.6680
Epoch 13/100
250/250 [==============================] - 0s 2ms/step - loss: 50514.9531 - mae: 50514.9531 - val_loss: 50954.0742 - val_mae: 50954.0742
Epoch 14/100
250/250 [==============================] - 0s 2ms/step - loss: 50377.0195 - mae: 50377.0195 - val_loss: 50875.5703 - val_mae: 50875.5703
Epoch 15/100
250/250 [==============================] - 0s 2ms/step - loss: 50288.3398 - mae: 50288.3398 - val_loss: 50826.2812 - val_mae: 50826.2812
Epoch 16/100
250/250 [==============================] - 0s 2ms/step - loss: 50217.4531 - mae: 50217.4531 - val_loss: 50776.0508 - val_mae: 50776.0508
Epoch 17/100
250/250 [==============================] - 0s 2ms/step - loss: 50160.3789 - mae: 50160.3789 - val_loss: 50743.5195 - val_mae: 50743.5195
Epoch 18/100
250/250 [==============================] - 0s 2ms/step - loss: 50112.5547 - mae: 50112.5547 - val_loss: 50714.3477 - val_mae: 50714.3477
Epoch 19/100
250/250 [==============================] - 0s 2ms/step - loss: 50067.9219 - mae: 50067.9219 - val_loss: 50676.2812 - val_mae: 50676.2812
Epoch 20/100
250/250 [==============================] - 0s 2ms/step - loss: 50028.4102 - mae: 50028.4102 - val_loss: 50651.1484 - val_mae: 50651.1484
Epoch 21/100
250/250 [==============================] - 0s 2ms/step - loss: 49992.6484 - mae: 49992.6484 - val_loss: 50614.1211 - val_mae: 50614.1211
Epoch 22/100
250/250 [==============================] - 0s 2ms/step - loss: 49958.6523 - mae: 49958.6523 - val_loss: 50592.0625 - val_mae: 50592.0625
Epoch 23/100
250/250 [==============================] - 1s 2ms/step - loss: 49931.0195 - mae: 49931.0195 - val_loss: 50572.1367 - val_mae: 50572.1367
Epoch 24/100
250/250 [==============================] - 1s 2ms/step - loss: 49897.1094 - mae: 49897.1094 - val_loss: 50553.9727 - val_mae: 50553.9727
Epoch 25/100
250/250 [==============================] - 0s 2ms/step - loss: 49873.6992 - mae: 49873.6992 - val_loss: 50530.2383 - val_mae: 50530.2383
Epoch 26/100
250/250 [==============================] - 0s 2ms/step - loss: 49847.9102 - mae: 49847.9102 - val_loss: 50518.6992 - val_mae: 50518.6992
Epoch 27/100
250/250 [==============================] - 0s 2ms/step - loss: 49826.9375 - mae: 49826.9375 - val_loss: 50505.2461 - val_mae: 50505.2461
Epoch 28/100
250/250 [==============================] - 0s 2ms/step - loss: 49807.1055 - mae: 49807.1055 - val_loss: 50482.6953 - val_mae: 50482.6953
Epoch 29/100
250/250 [==============================] - 0s 2ms/step - loss: 49784.9883 - mae: 49784.9883 - val_loss: 50466.1250 - val_mae: 50466.1250
Epoch 30/100
250/250 [==============================] - 0s 2ms/step - loss: 49767.9219 - mae: 49767.9219 - val_loss: 50451.8594 - val_mae: 50451.8594
Epoch 31/100
250/250 [==============================] - 0s 2ms/step - loss: 49751.8164 - mae: 49751.8164 - val_loss: 50437.4805 - val_mae: 50437.4805
Epoch 32/100
250/250 [==============================] - 0s 2ms/step - loss: 49731.4961 - mae: 49731.4961 - val_loss: 50427.7031 - val_mae: 50427.7031
Epoch 33/100
250/250 [==============================] - 0s 2ms/step - loss: 49713.0039 - mae: 49713.0039 - val_loss: 50415.4141 - val_mae: 50415.4141
Epoch 34/100
250/250 [==============================] - 1s 2ms/step - loss: 49700.4492 - mae: 49700.4492 - val_loss: 50406.0625 - val_mae: 50406.0625
Epoch 35/100
250/250 [==============================] - 0s 2ms/step - loss: 49687.6133 - mae: 49687.6133 - val_loss: 50394.0898 - val_mae: 50394.0898
Epoch 36/100
250/250 [==============================] - 0s 2ms/step - loss: 49669.8086 - mae: 49669.8086 - val_loss: 50385.7461 - val_mae: 50385.7461
Epoch 37/100
250/250 [==============================] - 0s 2ms/step - loss: 49654.6094 - mae: 49654.6094 - val_loss: 50375.1875 - val_mae: 50375.1875
Epoch 38/100
250/250 [==============================] - 0s 2ms/step - loss: 49640.7812 - mae: 49640.7812 - val_loss: 50362.7109 - val_mae: 50362.7109
Epoch 39/100
250/250 [==============================] - 0s 2ms/step - loss: 49631.1367 - mae: 49631.1367 - val_loss: 50359.3164 - val_mae: 50359.3164
Epoch 40/100
250/250 [==============================] - 0s 2ms/step - loss: 49616.9922 - mae: 49616.9922 - val_loss: 50365.0742 - val_mae: 50365.0742
Epoch 41/100
250/250 [==============================] - 0s 2ms/step - loss: 49604.7031 - mae: 49604.7031 - val_loss: 50358.6602 - val_mae: 50358.6602
Epoch 42/100
250/250 [==============================] - 0s 2ms/step - loss: 49597.0625 - mae: 49597.0625 - val_loss: 50361.9297 - val_mae: 50361.9297
Epoch 43/100
250/250 [==============================] - 0s 2ms/step - loss: 49583.5938 - mae: 49583.5938 - val_loss: 50337.1758 - val_mae: 50337.1758
Epoch 44/100
250/250 [==============================] - 0s 2ms/step - loss: 49573.6602 - mae: 49573.6602 - val_loss: 50346.8711 - val_mae: 50346.8711
Epoch 45/100
250/250 [==============================] - 0s 2ms/step - loss: 49559.9844 - mae: 49559.9844 - val_loss: 50343.7070 - val_mae: 50343.7070
Epoch 46/100
250/250 [==============================] - 0s 2ms/step - loss: 49551.2969 - mae: 49551.2969 - val_loss: 50352.0078 - val_mae: 50352.0078
Epoch 47/100
250/250 [==============================] - 0s 2ms/step - loss: 49545.5039 - mae: 49545.5039 - val_loss: 50353.2461 - val_mae: 50353.2461
Epoch 48/100
250/250 [==============================] - 0s 2ms/step - loss: 49531.7773 - mae: 49531.7773 - val_loss: 50373.6562 - val_mae: 50373.6562
Epoch 49/100
250/250 [==============================] - 0s 2ms/step - loss: 49522.5977 - mae: 49522.5977 - val_loss: 50349.2344 - val_mae: 50349.2344
Epoch 50/100
250/250 [==============================] - 0s 2ms/step - loss: 49515.2461 - mae: 49515.2461 - val_loss: 50340.6953 - val_mae: 50340.6953
Epoch 51/100
250/250 [==============================] - 0s 1ms/step - loss: 49508.7422 - mae: 49508.7422 - val_loss: 50354.1641 - val_mae: 50354.1641
Epoch 52/100
250/250 [==============================] - 1s 2ms/step - loss: 49502.0312 - mae: 49502.0312 - val_loss: 50365.3750 - val_mae: 50365.3750
Epoch 53/100
250/250 [==============================] - 0s 2ms/step - loss: 49496.8008 - mae: 49496.8008 - val_loss: 50351.5469 - val_mae: 50351.5469

In [16]:
%load_ext tensorboard

In [17]:
%tensorboard --logdir regressionlogs/fit

In [18]:
## Evaluate model on the test data
test_loss,test_mae=model.evaluate(X_test,y_test)
print(f'Test MAE : {test_mae}')

63/63 [==============================] - 0s 1ms/step - loss: 50337.1758 - mae: 50337.1758
Test MAE : 50337.17578125

In [19]:
model.save('regression_model.h5')

/Users/syedsaifullahtarique/Desktop/work/Udemy/Udemy_projects/Krish_naik_genai_with_langchain_huggingface/ANN_project/venv/lib/python3.11/site-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(